from .nodes.modal_register_output import NODE_CLASS_MAPPINGS as MODAL_REGISTER_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as MODAL_REGISTER_DISPLAY

NODE_CLASS_MAPPINGS = {
    **MODAL_REGISTER_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **MODAL_REGISTER_DISPLAY,
}

WEB_DIRECTORY = "./web"
__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
